apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatapp.fullname" . }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:

      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for MongoDB..."
              until nc -z {{ include "chatapp.fullname" . }}-mongo 27017; do
                echo "MongoDB not ready..."
                sleep 3
              done
              echo "MongoDB ready!"

      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: Always

          ports:
            - containerPort:  {{ .Values.service.backendPort }}

          env:
            - name: PORT
              value: "5000"

            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "chatapp.fullname" . }}-backend-secret
                  key: MONGODB_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "chatapp.fullname" . }}-backend-secret
                  key: JWT_SECRET

            - name: CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "chatapp.fullname" . }}-backend-secret
                  key: CLIENT_URL

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 40
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi