backend:
  image: kayesha01/chat-app-backend
  tag: latest
  replicas: 2

frontend:
  image: kayesha01/chat-app-frontend
  tag: latest
  replicas: 2

mongo:
  image: mongo
  tag: "7"
  storage: 5Gi

autoscaling:
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 50

service:
  backendPort: 5000
  frontendPort: 80
  mongoPort: 27017